url: https://josephborjon.com
name: Joseph Borjon
description: Increase your reach with Joseph Borjon, a US-based writer for hire specializing in B2B and B2C copywriting and content writing services in tech and business.
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      author: Joseph Borjon
      layout: article
  -
    scope:
      path: "portfolio/*.md"
      type: "pages"
    values:
      article_type: post

exclude:
  - notes/
  - favicons/favicon.xcf
  - images/original/
  - scripts/unminified/

compress_html:
  clippings: all
